Uza/Uza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Uza/app/urls.py
from django.urls import path 
from . import views
app_name = 'app'
urlpatterns=[
    path("", views.index, name ='home'),
    path('getintouch/', views.register, name ='getintouch'),
    path('work/', views.work, name = 'work'),
    path('privacy/', views.privacy , name = 'privacy'),
    path('about/', views.about, name = 'about'),
]

Uza/app/models.py
from django.db import models

class CustomerInfo(models.Model):
    branding = models.BooleanField()
    marketing = models.BooleanField()
    design = models.BooleanField()
    name = models.CharField(max_length=256)
    email = models.EmailField()
    phonenumber = models.PositiveIntegerField()
    tellus = models.TextField()

    def __str__(self):
        return self.name

Uza/migrate/models.py
from django.db import models

# Create your models here.

Uza/app/forms.py
# from django import forms

# CHOICES= [
#     ('Branding', 'Branding'),
#     ('Marketing', 'Marketing'),
#     ('mango', 'Mangoes'),
#     ('honeydew', 'Honeydews'),
#     ]

# class UserForm(forms.Form):
#     first_name= forms.CharField(max_length=100)
#     last_name= forms.CharField(max_length=100)
#     email= forms.EmailField()
#     age= forms.IntegerField()
#     favorite_fruit= forms.CharField(label='What is your favorite fruit?', widget=forms.RadioSelect(choices=FRUIT_CHOICES))
from django import forms 
from .models import CustomerInfo

class CustomerForm(forms.ModelForm):
    class Meta():
        model = CustomerInfo
        fields = '__all__'

Uza/app/views.py
from . import models
from django.shortcuts import render
from . import forms

# Create your views here.
def index(request):
    return render(request,'index.html')

def privacy(request):
    return render(request, 'pages/privacy.html')

def service(request):
    return render(request, 'pages/service.html')

def work(request):
    return render(request, 'pages/work.html')
def about(request):
    return render(request, 'pages/about.html')

def register(request):


    if request.method == 'POST':

        user_form = forms.CustomerForm(request.POST)
     
        if user_form.is_valid():
            user = user_form.save()
        else:
            print(user_form.errors)

    else:

        user_form = forms.CustomerForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'pages/getintouch.html',
                          {'user_form':user_form})

Uza/migrate/views.py
from django.shortcuts import render

# Create your views here.

Uza/app/templates/pages/privacy.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

    <link rel="stylesheet" href="../css/style.css" type="text/css" />

    <title>Hello, world!</title>
  </head>
  <body>
    <!-- Start your project here-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="index.html">
          <img src="../img/Uzability Logo-01.png" style="width: 80px;margin-left: 30px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="about.html">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="service.html">Services</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Projects
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="work.html">Work</a></li>
                <li><a class="dropdown-item" href="ulesson.html">Analysis</a></li>
                <li><a class="dropdown-item" href="ulesson.html">Branding</a></li>
                <li><a class="dropdown-item" href="ulesson.html">Customer Experience</a></li>
                <li><a class="dropdown-item" href="ulesson.html">Digital Design</a></li>
                <li><a class="dropdown-item" href="ulesson.html">Experience</a></li>
              </ul>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="getintouch.html"  >Get in touch</a>
            </li>
          </ul>
          <form class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-dark" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 style="font-size: 70px;margin-top: 100px;">Privacy policy
            </h1>

            <p style="font-size:22px;margin-top: 100px;">
                Effective date: December 17, 2018<br><br>

Cuberto Inc ("us", "we", or "our") operates the <a href="https://www.uza.studio/" style="font-weight: bold;color: #000;">https://www.uza.studio/ </a> website (the "Service").
<br><br>
This page informs you of our policies regarding the collection, use, and disclosure of personal data when you use our Service and the choices you have associated with that data.
<br><br>
We use your data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this policy. Unless otherwise defined in this Privacy Policy, terms used in this Privacy Policy have the same meanings as in our Terms and Conditions, accessible from https://www.uza.studio/ 
            </p>
        </div>
    </div>
</div>


<div class="container">
   <div class="row">
       <div class="col-md-12">
           <h3 style="font-size: 40px;margin-top: 50px;">Information Collection And Use</h3>

           <p style="font-size:22px;margin-top: 50px;">We collect several different types of information for various purposes to<br> provide and improve our Service to you.

        </p>
       </div>
   </div>
</div>

<footer style="background-color: black;padding: 50px;margin-top: 100px;">


  <div class="container">
     <div class="row">
       <div class="col-md-3">
       <a href="{% url 'app:getintouch' %}" >
        <p style="color:#fff" class="hvr-underline-from-center"> Get in touch</p>
      </a> 
           <br>
      <a href="{% url 'app:about' %}" >
        <p style="color:#fff" class="hvr-underline-from-center"> About US</p>
      </a> 
      <br>
      <a href="{% url 'app:work' %}" >
        <p style="color:#fff" class="hvr-underline-from-center"> Projects</p>
      </a> 
      <br>
      <a href="{% url 'app:home' %}" >
        <p style="color:#fff" class="hvr-underline-from-center"> Home</p>
      </a> 
       </div>
      
       <div class="col-md-3" style ='margin-left:130px;'>
       <p style="color:#fff">Riyadh<p style="color:#fff">Jeddah</p><p style="color:#fff">Eastern Province</p><p style="color:#fff">Neom</p></p> 
       <br>
       <a href="#"><i class="fab fa-twitter" style="color:white"></i></a>&nbsp;&nbsp;&nbsp;<a href="#"><i class="fab fa-facebook-square" style="color:white"></i></a>&nbsp;&nbsp;&nbsp;<a href="#"><i class="fab fa-linkedin-in" style="color:white"></i></a>&nbsp;&nbsp;&nbsp;<a href="#"><i class="fab fa-youtube" style="color:white"></i></a> 
       </div>
       <div class="col-md-3" style = 'margin-left:130px;'>
         <p style="color:#fff">Uzability Design Studio</p>
         <p style="color:rgba(238, 238, 238, 0.534)">Copyright @2021 <br>
          All Rights Reeserved.</p>
       </div>
     </div>
  </div>

  </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
    </body>
    </html>